function [v_fitted] = func_genACVolWithCFCA(v)
%% 08/06/2019, Jisoo Choi

[fitresult, ~] = createFit(v);
x = 1:length(v);
v_fitted = fitresult.a1*sin(fitresult.b1*x + fitresult.c1);
v_fitted = v_fitted(:);


function [fitresult, gof] = createFit(v)
%CREATEFIT(V)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: v
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Aug-2019 21:07:24


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], v );

% Set up fittype and options.
ft = fittype( 'sin1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0.068 0 -Inf];
opts.StartPoint = [0.07 0.00855244388943172 1.48628663343297];
opts.Upper = [0.071 Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'v', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% ylabel v
% grid on


